sudo: required

language: python

cache:
  pip: true
  directories:
    - node_modules

python:
  - "3.6"

services:
  - docker

addons:
  apt:
    packages:
      - nodejs

before_install:
  - pip install -r tools/requirements.txt
  - npm install

install:
  - echo building HTML
  - python tools/jinjer/jinjer.py src/html server/swissvoice/static
  - echo building CSS
  - python tools/sassier/sassier.py src/css server/swissvoice/static/css
  - echo building JS
  - npm run-script build

script:
  - echo success

before_deploy:
  - echo building docker image...
  - docker build -t "$DOCKER_REPO" ./server

deploy:
  provider: script
  script: bash ./.travis/docker_push.sh
  on:
    all_branches: true