version: "3"

services:
  app:
    container_name: SwissVoice
    build: .
    image: swissvoice
    restart: always
    ports:
      - 80:80
    volumes:
      - ./swissvoice/static:/app/swissvoice/static
    networks:
      - backend
    depends_on:
      - database
    environment:
      - SW_MONGODB_URI
      - SW_SENTRY_DSN
      - SW_S3_ENDPOINT_URL
      - SW_S3_ACCESS_KEY
      - SW_S3_SECRET_ACCESS_KEY
      - SW_RECORDING_LOCATION
  database:
    container_name: SwissVoice_MongoDB
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - swissvoice:/data/db
      - swissvoice:/data/configdb
    networks:
      - backend

volumes:
  swissvoice: {}

networks:
  backend: {}